#!/bin/bash

# Reorganize src/ folder for clean separation of file types
# This script will:
# 1. Move all test files to tests/ directory maintaining structure
# 2. Remove compiled JS files (they belong in dist/)
# 3. Clean up the src/ to only contain TypeScript source files

echo "🧹 Reorganizing src/ folder for clean file type separation..."

# Function to move test files while preserving directory structure
move_tests() {
    echo "📝 Moving test files to tests/ directory..."
    
    # Find all .test.ts files and move them to tests/ preserving structure
    find src -name "*.test.ts" -type f | while read -r file; do
        # Get the relative path from src/
        rel_path=${file#src/}
        # Create target directory in tests/
        target_dir="tests/$(dirname "$rel_path")"
        mkdir -p "$target_dir"
        # Move the file
        mv "$file" "tests/$rel_path"
        echo "  Moved: $file → tests/$rel_path"
    done
}

# Function to remove compiled artifacts
remove_compiled() {
    echo "🗑️  Removing compiled artifacts from src/ (they belong in dist/)..."
    
    # Remove .js files
    find src -name "*.js" -type f -delete
    echo "  Removed all .js files"
    
    # Remove .js.map files
    find src -name "*.js.map" -type f -delete
    echo "  Removed all .js.map files"
    
    # Remove .d.ts files (except hand-written ones)
    find src -name "*.d.ts" -type f -delete
    echo "  Removed all .d.ts files"
    
    # Remove .d.ts.map files
    find src -name "*.d.ts.map" -type f -delete
    echo "  Removed all .d.ts.map files"
}

# Function to organize remaining files
organize_source() {
    echo "📁 Organizing remaining TypeScript source files..."
    
    # List what's left
    echo "📊 Remaining files in src/:"
    find src -name "*.ts" -type f | head -20
    echo "..."
    total_ts=$(find src -name "*.ts" -type f | wc -l)
    echo "  Total TypeScript files: $total_ts"
}

# Create tests directory if it doesn't exist
mkdir -p tests

# Execute reorganization steps
move_tests
remove_compiled
organize_source

echo ""
echo "✅ src/ folder reorganization complete!"
echo ""
echo "📁 New structure:"
echo "  • src/ - Only TypeScript source files (.ts)"
echo "  • tests/ - All test files (.test.ts) with preserved directory structure"  
echo "  • dist/ - Compiled artifacts (generated by build process)"
echo ""
echo "🔧 Next steps:"
echo "  • Update jest.config.cjs to look for tests in tests/ directory"
echo "  • Update tsconfig.json if needed"
echo "  • Run 'npm run build' to regenerate dist/"
echo "  • Run 'npm test' to verify tests still work"